### ISSUE TITLE
GOOGLE_SHEET_CONNECTOR issue

### ISSUE THREAD

**Issue by ok-timmy** [johnkhansrc/NestGoogleSheetConnector#1]
I stumbled on this Bug while trying to implement this.

I tried implementing this module in my project, however, I am getting this error below in the console when I try to run the code.

[Nest] 8080  - 07/12/2023, 7:26:25 PM     LOG [NestFactory] Starting Nest application...
[Nest] 8080  - 07/12/2023, 7:26:25 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the GoogleAuthService (?). Please make sure that the argument GOOGLE_SHEET_CONNECTOR at index [0] is available in the AppModule context.

Potential solutions:
- Is AppModule a valid NestJS module?
- If GOOGLE_SHEET_CONNECTOR is a provider, is it part of the current AppModule?
- If GOOGLE_SHEET_CONNECTOR is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing GOOGLE_SHEET_CONNECTOR */ ]
  })

Error: Nest can't resolve dependencies of the GoogleAuthService (?). Please make sure that the argument GOOGLE_SHEET_CONNECTOR at index [0] is available in the AppModule context.

<img width="760" alt="image" src="https://github.com/johnkhansrc/NestGoogleSheetConnector/assets/94664656/7182ccfb-deda-4157-ab2b-8e1db73dad3d">

**Comment by johnkhansrc** [comment]
Good morning.

Indeed, the documentation is not maintained and I lack time to develop the project, there are many methods to optimize and features to add.

I will however try to unblock you.

First you will need an .env with the following keys:
```
SPREADSHEET_ID=XXXXXXX
GOOGLE_SHEET_CREDENTIALS=XXXXXX
```

Here is an example implementation:
```ts
@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: ['.env'],
      isGlobal: true,
    }),
    GoogleSheetModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

Any PR is welcome if you want to improve the project.
