### ISSUE TITLE
SSL Certificate issue

### ISSUE THREAD

**Issue by ok-timmy** [johnkhansrc/NestGoogleSheetConnector#2]
Hello John,

Could you please give a detailed explanation of how to fet the SSL cerificate locally on my PC, because I have tried running the command in my terminal and I keep getting an error message?

And yex, thanks for the last update, the code works. I am just stuck at the SSL certificate part.

**Comment by ok-timmy** [comment]
If you got stuck on this part, I figured it out.

You can check this article to install SSL on your machine in case you don't have.

https://www.stechies.com/installing-openssl-windows-10-11/

**Comment by johnkhansrc** [comment]
Hello ok-timmy.

Unfortunately I don't have enough time to maintain this project.
If possible, I invite you to fork and make a PR to contribute.

- Create a personal fork of the project on Github.
- Clone the fork on your local machine. Your remote repo on Github is called origin.
- Add the original repository as a remote called upstream.
- If you created your fork a while ago be sure to pull upstream changes into your local repository.
- Create a new branch to work on! Branch from develop if it exists, else from master.
- Implement/fix your feature, comment your code.
- Follow the code style of the project, including indentation.
- If the project has tests run them!
- Write or adapt tests as needed.
- Add or change the documentation as needed.
- Squash your commits into a single commit with git's [interactive rebase](https://help.github.com/articles/interactive-rebase). Create a new branch if necessary.
- Push your branch to your fork on Github, the remote origin.
- From your fork open a pull request in the correct branch. Target the project's develop branch if there is one, else go for master!
- ...
- Once the pull request is approved and merged you can pull the changes from upstream to your local repo and delete your extra branch(es).
