### ISSUE TITLE
Invalid_value at "value_input_option"

### ISSUE THREAD

**Issue by ok-timmy** [johnkhansrc/NestGoogleSheetConnector#3]
I came across this error again while trying to implement the write cell function. 

<img width="784" alt="image" src="https://github.com/johnkhansrc/NestGoogleSheetConnector/assets/94664656/500f45fb-a421-4e86-9bfa-cd34dc5b2889">

I guess the error came from the writeRange method. I think It should have been either "RAW" or "USER_ENTERED" and not "USER_ENTER"

This same error occurs on the writeRange function.

**Comment by ok-timmy** [comment]
Issue resolved

**Comment by devglrd** [comment]
Hi @ok-timmy How did you resolve this error ?

**Comment by ok-timmy** [comment]
The package has been resolved. 
The issue came with the package, but I made a pull request few months back which has been merged.
You can try it out again according to how it's written on the ReadMe file.
