### ISSUE TITLE
Invalid_value at "value_input_option" again

### ISSUE THREAD

**Issue by Vozis** [johnkhansrc/NestGoogleSheetConnector#6]
For now version 2.0.0 is available for download in npm. Here is the error  "Invalid value at 'value_input_option' (type.googleapis.com/google.apps.sheets.v4.ValueInputOption), "USER_ENTER" ". How to download 2.0.1 ?

**Comment by devglrd** [comment]
Hi @johnkhansrc Please release the 2.0.1 version

**Comment by johnkhansrc** [comment]
Merged in https://github.com/johnkhansrc/NestGoogleSheetConnector/pull/7
